### ISSUE TITLE
Search component only starts searching after hitting the search button

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#150]
When searching (e.g. in the plugin help center), the user must hit the search button/enter to start searching. It would be nicer when this extra step wouldn't be necessary.

![schermafbeelding 2017-06-16 om 15 06 52](https://user-images.githubusercontent.com/17744553/27227845-74b02976-52a5-11e7-9d34-c1e9f55d2b14.png)

**Comment by afercia** [comment]
Not sure we should try any of this :) will comment expanding the whys as soon as possible.

**Comment by afercia** [comment]
In WordPress core we've researched a bit about this topic, see https://core.trac.wordpress.org/ticket/31818 and some of the things observed there apply to the "search as you type" live search (or whatever we want to call it). Trying to compare the interaction differences between a "classical" search and a "live" search, the first things that come into my mind are (I may miss something):

"classical" search:
- type the search term
- don't worry for typos: you can always edit the field and fix them before hitting the button
- don't worry for typing speed: the search is triggered only with an explicit user action
- just one request/response for each search
- field+button: no surprises for users
- assistive technologies know what to do with a field+button
- from an a11y perspective we just had the need to announce the search results, since there's no page reload
- it just works

"live-search" (or "search as you type"):
- no button
- users need to be informed the search results will appear "as you type"
- type the search term
- after how many characters the search should fire?
- the search should fire when users stop typing: this requires "detecting" typing, catching the keydown event (excluding arrow keys) or props change and debouncing the search
- not all users type at the same speed: not sure a fixed delay to debounce the search will fit all users needs
- fixing typos in the typed search term is more difficult, as in the meantime it is very likely the search will be triggered
- it's very likely there will be multiple search triggered for a single search term because of typos, typing speed, etc.
- it works well for some users, but not for all users

That said, we can certainly experiment a bit and try to make a nice, accessible, "live search". However, I'm wondering if the little gain a more reactive and dynamic interface will bring is worth the effort.

**Comment by IreneStr** [comment]
Optional live search and search button have been implemented in #316
