### ISSUE TITLE
Implement ProgressBar Component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#157]
Using styled components, implement a `ProgressBar` component with the following props:
- minimumValue `number` The minimum value
- maximumValue `number` The maximum value
- currentValue `number` The current value

Don't forget to add `aria-hidden="true"` since we want to hide the progress bar for screen readers as long as we haven't found a way to announce it properly (see: https://github.com/Yoast/YoastSEO.js/issues/466)

![schermafbeelding_2017-07-14_om_12_05_37](https://user-images.githubusercontent.com/17744553/28208273-36ee191a-688d-11e7-92f3-725376ba4496.png)

Please put this component in the SnippetPreview folder.

**Comment by hedgefield** [comment]
As per https://github.com/Yoast/wordpress-seo/issues/3866, the progress bar should have a few extra design elements:

- A ::before and ::after which is are white boxes of 2px wide, with matching borders on the left and right edges, and place those at the relative positions (left: 30%, right 10%). This will visually make it appear to be 3 separate boxes while keeping it as one progress bar. (ask jip if you need help with this)
- A text label next to the progress bar on the left which communicates textually the state that the bar is in (_too short, ideal range, too long_). Font is the default font used, size at about 0.75em.
- When the progress bar reaches the _too long_ section it should turn red. The values for the progress bar should be tweaked a little too, because now there isn't really a _too long_ section to it, it only changes color again once the bar has reached 100% and you keep typing.

Below is a mockup:

![snippet preview progress bars](https://user-images.githubusercontent.com/6073772/29269649-da87a708-80f2-11e7-8086-7ea6c1b70147.png)

**Comment by IreneStr** [comment]
@hedgefield Thanks! I've created a separate issue: #226
