### ISSUE TITLE
Implement ContentAnalysis component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#194]
Using styled components, implement a ContentAnalysis component.

This component is a combination the AnalysisHeader (#192) and the AnalysisResults (#191).

Please use react-intl's FormattedMessage to insert the number of problems/improvements/good and to make the texts translatable.

<img width="644" alt="seo_analysis_reactified_4_psd___100___layer_2__rgb_8__" src="https://user-images.githubusercontent.com/6073772/29066155-ab4ccb30-7c2e-11e7-87a8-7ba29ecb3a4c.png">

Please put this component in the ContentAnalysis folder.

When count = 0 for one of the categories, the header should not be shown.

**Comment by Xyfi** [comment]
Make sure the language notice is implemented in this component:

https://github.com/Yoast/yoast-components/issues/208

**Comment by afercia** [comment]
About the language notice, the only a11y concern is making the "Change" link understandable also when read out of context:

<img width="757" alt="metabox_reactified_4_psd___100___your_site_language_is_set_to_english__change__rgb_8__" src="https://user-images.githubusercontent.com/6073772/29070295-061d2dba-7c3f-11e7-8072-cec7c65ff429.png">

`Change language` instead of just `Change` would be nice.
