### ISSUE TITLE
Help Center styling tweaks

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#329]
- [ ] Fix alignment of the help center paper:
    - [ ] On the settings pages: align the left with metabox underneath it, align right with the end of the grey line above the help center.
    - [ ] On the posts and pages page: Don't change the help center paper, but align the Yoast metabox with the help center paper (decrease width)
- [ ] Center the content of the get support and video tutorial tab
- [ ] The width of the Algolia search results should be increased to the width of the search bar + the width of the search button.
- [ ] Add a little bit more margin at the bottom of the `need help?` button
- [ ] Set the max-width for the content of the YoastTabs + delete max-width on individual components

**Comment by afercia** [comment]
> On the settings pages: align the left with metabox underneath it, align right with the end of the grey line above the help center.

Not sure there is a real "metabox" in the settings pages. Normal setting pages have normal content, the alignment seems good to me:

![screen shot 2017-10-06 at 16 36 36](https://user-images.githubusercontent.com/1682452/31283394-c40ca45a-aab5-11e7-86a9-4b078c86479f.png)

Only in the Settings Dashboard there are the "Alerts papers" (the white boxes):

![screen shot 2017-10-06 at 16 37 43](https://user-images.githubusercontent.com/1682452/31284739-bff5bf42-aab9-11e7-90bf-a3d2ae1e685c.png)

and the alignment of the "Alerts papers" is a bit off because they're wrapped in one more element with class `.wrap` : this is a WP class that should be used just once on the main wrapper and adds some left/right padding:

<img width="816" alt="screen shot 2017-10-06 at 16 38 06" src="https://user-images.githubusercontent.com/1682452/31284813-f5540fa4-aab9-11e7-9766-409e56cf95f9.png">

**Comment by afercia** [comment]
> On the posts and pages page: Don't change the help center paper, but align the Yoast metabox with the help center paper (decrease width)

Actually, the Help Center is _inside_ the metabox. Not sure I understand the request. Should the metabox _content_ have a `max-width: 900px` and be centered?

This is how it looks now:

![screen shot 2017-10-06 at 18 08 21](https://user-images.githubusercontent.com/1682452/31288605-e9faa01c-aac5-11e7-84f0-152ca0c7bebf.jpg)

**Comment by afercia** [comment]
>  Center the content of the get support and video tutorial tab

Seems to me it is already centered?

**Comment by afercia** [comment]
> The width of the Algolia search results should be increased to the width of the search bar + the width of the search button.

I think this has already been fixed, was because of a conflict with a max-width inherited from the plugin.
