### ISSUE TITLE
Breadcrumbs in React snippet preview are cut off by question mark and hash

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#485]
### How can we reproduce this behavior?
1. Use define( 'YOAST_FEATURE_SNIPPET_PREVIEW', true ); to show the React SnippetPreview.
2. Open the snippet editor of the React snippet preview and make sure it's showing the mobile view. Write a slug and look at the breadcrumbs.
3. Add a question mark somewhere in the middle of your slug.
4. See that the breadcrumb only contains the part before the question mark.

The same happens when you use a #.

### To do
Because WordPress strips ? and # from the slug in the permalink editor, we should do that as well.

**Comment by afercia** [comment]
Seems to me the issue here is because `getBreadcrumbs()` uses `parse` from the `node-url` package which considers anything that comes after a `?` a query string and anything that comes after a `#` an URL fragment identifier.  It correctly returns them in the `search` and `hash` parts of the parsed URL but we're not using them.
So yes, I guess the most reasonable option is to just strip out any `?` and `#` from the URL _before_ passing it to `parse( url )`.
