### ISSUE TITLE
Use error boundaries for the Snippet editor replacement (mentions plugin)

### ISSUE THREAD

**Issue by afercia** [Yoast/yoast-components#591]
Splitting this out from #584.

Turns out there's a bug in the Mentions plugin that makes Microsoft Edge crash the snippet editor app in some edge cases. The issue was reported upstream, see https://github.com/draft-js-plugins/draft-js-plugins/issues/1124

In the meantime, we should try to use error boundaries to workaround this.

**Comment by IreneStr** [comment]
The idea is to either:
- Throw an error and reinitialize (preferred solution)
- Thrown an error and explain the user should reload the page.

**Comment by boblinthorst** [comment]
I tried to fix this, but I had trouble fixing something that I couldn't reproduce entirely without edge. 

what I tried, was throwing an error on change in index.js of the mentions plugin:
```
    onChange: function onChange(editorState) {
	  throw new Error( "it went horribly wrong" );
```

And then proceeding to catch the error using the principle of the error boundary in replacementVariableStandalone.js. The following I added in the component: 

```
	componentDidCatch( error, errorInfo ) {
		console.log( "Caught by componentDidCatch." );
		// Catch errors in any components below and re-render with error message
		this.setState( {
			error: error,
			errorInfo: errorInfo
		} );
	}
```

and I changed the render function to the following:
```
	render() {
		const {MentionSuggestions} = this.mentionsPlugin;
		const {onFocus, onBlur, ariaLabelledBy, placeholder} = this.props;
		const {editorState, replacementVariables} = this.state;
		if ( this.state.error ) {
			return <p> something whent wrong, please reload the page. </p>;
		}
		else {
			return (
				<React.Fragment>
					<Editor
						editorState={ editorState }
						onChange={ this.onChange }
						onFocus={ onFocus }
						onBlur={ onBlur }
						plugins={ [this.mentionsPlugin, this.singleLinePlugin] }
						ref={ this.setEditorRef }
						stripPastedStyles={ true }
						ariaLabelledBy={ ariaLabelledBy }
						placeholder={ placeholder }
					/>
					<ZIndexOverride>
						<MentionSuggestions
							onSearchChange={ this.onSearchChange }
							suggestions={ replacementVariables }
							ref={ this.setMentionSuggestionsRef }
						/>
					</ZIndexOverride>
				</React.Fragment>
			);
		}
	}
```
My goal was for the render function to not render the editor, and instead render the text. This did not work as intended yet.

I decided to distance myself from the issue for now, because I'm not even sure if the boundary is even fixing the edge error as I'm applying it.

**Comment by afercia** [comment]
Worth noting after I've successfully (and painfully) updated Windows, my Edge version is now:
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

and I can't reproduce the error any longer.
