### ISSUE TITLE
Fix alignment of snippet variable insert buttons in settings

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#594]
In the Settings > Search Appearance, the snippet variable inserter button is (unwantedly) located below the input field title, instead of next to it. When you make the window narrower and wider again, the buttons are (correctly) next to the input field title:

![button3](https://user-images.githubusercontent.com/17744553/41536167-18400694-7305-11e8-9062-cd5ef7383455.gif)
_My apologies for the bad gif quality. The filesize of a higher quality gif was too large to upload_

Find a way to make the variable insert button on the settings pages behave properly without using a timeout. See https://github.com/Yoast/yoast-components/pull/567/files/9d941e54ba280f095d9c8b1cd8721b125c919a3a..d49c1fe99cdc9ac4abfc2ea3c1d12079382bc051#diff-a6998dc55739e5697356856577694014R96
Without the time-out the button ended up behind the input field.

**Comment by afercia** [comment]
On my end, I can't reproduce this in Chrome. I can, sometimes, reproduce it in Firefox so I guess it really depends on timings.

**Comment by afercia** [comment]
OK so to my understanding it's really a timing issue in how browsers get `clientWidth` as it seems Firefox needs more time (however, as mentioned before this happens inconsistently)... 

Firefox:

![screen shot 2018-06-25 at 10 46 10](https://user-images.githubusercontent.com/1682452/41841541-e0239b54-7868-11e8-9a47-32e9fd43425b.png)

Chrome:

![screen shot 2018-06-25 at 10 46 26](https://user-images.githubusercontent.com/1682452/41841542-e04ec8a6-7868-11e8-8bc3-e90c5e6b640f.png)

Regardless of timings, there's a more general issue that makes this hard (if not impossible) to fix.

In the Settings pages there are multiple editors. They're all rendered even if they're not all visible because some of them are in other tabs or inside expandable panels. The widths calculation runs for all of them though. So even if the button is correctly positioned in the first visible tab:

<img width="787" alt="screen shot 2018-06-25 at 11 04 36" src="https://user-images.githubusercontent.com/1682452/41841866-a972fe8c-7869-11e8-91bb-0362e48f876b.png">

then when switching to another tab, the button is misplaced (even in Chrome) because the editor wasn't visible and thus its `clientWidth` was `0`:

<img width="812" alt="screen shot 2018-06-25 at 11 04 50" src="https://user-images.githubusercontent.com/1682452/41841911-c8ec4aa2-7869-11e8-9c9c-86f5fa77fa19.png">


The only way I see to fix this would be running the widths calculation every time a tab is clicked, but that's hard to do and adds an extra layer of complexity. I'd rather ditch the whole JS `updateIsSmallerThanMobileWidth` thing and take care of the button placement with just CSS.
